### ISSUE TITLE
Watchdog Node

### ISSUE THREAD

**Issue by MattWis** [OlinREVO/AVR-CAN#3]
A couple of our nodes will want to recieve all messages, without needing everyone to send messages to them.

I think it would be useful to use the NODE_broadcast for this, as in, in init_CAN

if (node_id == NODE_broadcast) {
    CANIDM1 = 0x00;
} else {
    CANIDM1 = 0xF8;
}

**Comment by redfern314** [comment]
Note: this issue is still active, as broadcast functionality hasn't been implemented yet.

**Comment by redfern314** [comment]
Note: this is still active, though we've recently been referring to this node as the watchdog (as opposed to broadcast, which is a different functionality).
